
baseURL = "http://atf.jace.pro/"
languageCode = "en-us"
title = "ATF"
theme = "hugograyscale"
#googleAnalytics = ""
[params]
    # Provide some metadata for search and indexing services
    description = "A port of the Grayscale theme to Hugo"
    author = "RunningStream"